<?php
/**
 * Created by PhpStorm.
 * User: 49176
 * Date: 10.03.2021
 * Time: 14:13
 */
include_once('./DB_Connection/cls_DB_Object.php');
require_once('./util/helper.php');

class tbl_session extends cls_DB_Object
{
  protected static $table_name = 'tbl_session';
  protected static $db_fields ;//= array('id', 'session', 'date');

  function __construct()
  {
    self::$db_fields = readFieldsOfTables(self::$table_name);
    foreach (self::$db_fields as $key)
    {
      $this->{$key} = null;
    }
  }

  public static $instance_count = 0;
  public static $sql_count = 0;
  public $authorization;


  public function save()
  {
    $this->authorization = authorizationVerify();
    if (!$this->authorization->access) {
      $this->changeConfirm_query(false);
      $this->session = session_id();
      $this->date = date('Y-m-d H:i');
//    validation() ;     // TODO: Change the autogenerated stub
      $return = parent::save();
      $this->changeConfirm_query(true);
      return $return;
    }
  }

  public $showFields = [];
  public function fields(){
    for ($i = 0; $i < count(self::$db_fields); $i++) {
      array_push($this->showFields, self::$db_fields[$i]);
    }
    return json_encode($this->showFields);
  }

}