<?php
/**
 * Created by PhpStorm.
 * User: 49176
 * Date: 10.03.2021
 * Time: 14:13
 */
include_once('./DB_Connection/cls_DB_Object.php');
require_once('./util/helper.php');

class tbl_session extends generalModels
{
  protected static $table_name = 'tbl_session';

  function __construct()
  {
    parent::__construct(self::$table_name);
  }


  public function save()
  {
    if (!$this->authorization->access) {
      $this->changeConfirm_query(false);
      $this->session = session_id();
      $this->date = date('Y-m-d H:i');
//    validation() ;     // TODO: Change the autogenerated stub
      $return = cls_DB_Object::save();
      $this->changeConfirm_query(true);
      return $return;
    }
  }

  public function select($jsonEncode = true, $field = '*')
  {
//    if ($this->authorization->access) {
    $field = makeFindAllFields(parent::fields());
    return cls_DB_Object::select($jsonEncode, $field);
//    }
  }




}