<?php
/**
 * Created by PhpStorm.
 * User: 49176
 * Date: 10.03.2021
 * Time: 14:13
 */
include_once('./DB_Connection/cls_DB_Object.php');

class tbl_session extends cls_DB_Object
{
  protected static $table_name = "tbl_session";
  protected static $db_fields = array("id", "session", "date");

  public $id;
  public $session;
  public $date;

  public static $instance_count = 0;
  public static $sql_count = 0;
  public $authorization;


  public function save()
  {
    $this->session = session_id();
    $this->date =  date("Y-m-d H:i");
//    validation() ;     // TODO: Change the autogenerated stub

    return parent::save();
  }

  public $showFields = [];
  public function setShowFields(){
    for ($i = 0; $i < count(self::$db_fields); $i++) {
      array_push($this->showFields, self::$db_fields[$i]);
    }
    return $this->showFields;
  }


}