<?php
/**
 * Created by PhpStorm.
 * User: 49176
 * Date: 29.10.2020
 * Time: 17:12
 */
include_once('./DB_Connection/cls_DB_Object.php');

class tbl_exam_date extends cls_DB_Object
{
  protected static $table_name = "tbl_exam_date";
  protected static $db_fields = array("id", "writtenExamDate", "oralExamData",
    "registrationDeadline", "lastRegistrationDeadline", "examTypes");

  public $id;
  public $writtenExamDate;
  public $oralExamData;
  public $registrationDeadline;
  public $lastRegistrationDeadline;
  public $examTypes;

  public static $instance_count = 0;
  public static $sql_count = 0;

  public function save()
  {
//    validation() ;     // TODO: Change the autogenerated stub
    $this->fillVariable();

    return parent::save();
  }


}